config/routes.rb
Rails.application.routes.draw do

  # API
  
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :companies, only: %i[ index ]
    end
  end


  get 'pages/dashboard'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'companies#index' 
  resources :companies  do
    resources :openings, except: %i[ new show index ]
    # new openings routes
    get 'mon', to: 'openings#mon', as: "mon"
    get 'tue', to: 'openings#tue', as: "tue"
    get 'wed', to: 'openings#wed', as: "wed"
    get 'thu', to: 'openings#thu', as: "thu"
    get 'fri', to: 'openings#fri', as: "fri"
    get 'sat', to: 'openings#sat', as: "sat"
    get 'sun', to: 'openings#sun', as: "sun"
    # check out company route
    get 'review', to: 'companies#review', as: "review"
  end

  devise_for :users
  # [...]
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :restaurants, only: [ :index ]
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_day.html.erb
<div class="content-container container">
  <div class="new-company-container">
    <h1>Now add <%= @company.name %>'s times:</h1>
      <%# @all_openings.each do |o| %>
        <%= link_to  "to review", company_review_path(@company) %>
        <%= simple_form_for [@company, @opening] do |f| %>
          <h2><%= @opening.day %>:</h2>
          <%= f.input :closed_day, label: "closed" %>
          <%= f.input :always_open, label: "24h" %>
          <h4>mornings</h4>
          <p>from:</p>
          <%= f.input :morning_opens_at_hours, label: "morning_opens_at_hours" %>
          <%= f.input :morning_opens_at_minutes, label: "morning_opens_at_minutes" %>

          <p>to:</p>
          <%= f.input :morning_closes_at_hours, label: "morning_closes_at_hours" %>
          <%= f.input :morning_closes_at_minutes, label: "morning_closes_at_minutes" %>

          <h4>afternoons</h4>
          <p>from:</p>
          <%= f.input :afternoon_opens_at_hours, label: "afternoon_opens_at_hours" %>
          <%= f.input :afternoon_opens_at_minutes, label: "afternoon_opens_at_minutes" %>

          <p>to:</p>
          <%= f.input :afternoon_closes_at_hours, label: "afternoon_closes_at_hours" %>
          <%= f.input :afternoon_closes_at_minutes, label: "morning_closes_at_minutes" %>

          <%= f.submit %>
        <% end %>
      <%# end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="grid-navbar">
  <%= link_to image_tag("logo.svg"), companies_path %>
  <!-- user Dropdown
    <p><i id= "UserDropBtn" class="user-drop-btn far fa-user-circle"></i></p>
    <div id= "UserDropMenu" class="user-drop-menu">
      <%# <ul class="drop-list"> %>
        <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "drop-item" %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "drop-item"%>
          <%= link_to "Sign up", new_user_registration_path, class: "drop-item" %>
        <% end %>
          <%= link_to "Add Company", new_company_path, class: "drop-item" %>
          <%= link_to  "Dashboard", pages_dashboard_path %>
      <%# </ul> %>
    </div>
  -->
</div>