config/routes.rb
Rails.application.routes.draw do

  # API
  
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :companies, only: %i[ index ]
    end
  end


  get 'pages/dashboard'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'companies#index' 
  resources :companies  do
    resources :openings, except: %i[ new show index ]
    # new openings routes
    get 'mon', to: 'openings#mon', as: "mon"
    get 'tue', to: 'openings#tue', as: "tue"
    get 'wed', to: 'openings#wed', as: "wed"
    get 'thu', to: 'openings#thu', as: "thu"
    get 'fri', to: 'openings#fri', as: "fri"
    get 'sat', to: 'openings#sat', as: "sat"
    get 'sun', to: 'openings#sun', as: "sun"
    # check out company route
    get 'review', to: 'companies#review', as: "review"
  end

  devise_for :users
  # [...]
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :restaurants, only: [ :index ]
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
# Be sure to restart your server when you modify this file.
class Company < ApplicationRecord

  belongs_to :user

  # Returns all openings associated, allows to fetch data accordingly
  # usage: Company.find_hours[:mon][:morning] => 10:00 - 12:00
  # todo change to class!
  def find_hours
    { mon:
      {
        all_day: match_time('Mon', 'allday'),
        morning: match_time('Mon', 'morning'),
        noon: match_time('Mon', 'noon'),
        day: 'Mon'
      },
      tue: {
        all_day: match_time('Tue', 'allday'),
        morning: match_time('Tue', 'morning'),
        noon: match_time('Tue', 'noon'),
        day: 'Tue'
      },
      wed: { 
        all_day: match_time('Wed', 'allday'),
        morning: match_time('Wed', 'morning'),
        noon: match_time('Wed', 'noon'),
        day: 'Wed'
      },
      thu: {
        all_day: match_time('Thu', 'allday'),
        morning: match_time('Thu', 'morning'),
        noon: match_time('Thu', 'noon'),
        day: 'Thu'
      },
      fri: {  
        all_day: match_time('Fri', 'allday'),
        morning: match_time('Fri', 'morning'),
        noon: match_time('Fri', 'noon'),
        day: 'Fri'
      },
      sat: { 
        all_day: match_time('Sat', 'allday'),
        morning: match_time('Sat', 'morning'),
        noon: match_time('Sat', 'noon'),
        day: 'Sat'
      },
      sun: { 
        all_day: match_time('Sun', 'allday'),
        morning: match_time('Sun', 'morning'),
        noon: match_time('Sun', 'noon'),
        day: 'Sun'
      },
      all_openings: display_all_openings
    }
  end
  
  def opening_hours
    find_hours[:all_openings]
  end
  
  private

  # checks if the Opening is a Normal day, a Closed day or a 24H day.
  def check_hour(o)
    if o.closed_day
      'Closed'
    elsif o.always_open
      '24H'
    else
      true
    end
  end

  # Return formatted hours
  def return_hours(time, o)
    case time
    when 'morning'
      morning_format(o)
    when 'noon'
      noon_format(o)
    when 'allday'
      allday_format(o)
    end
  end

  # Used on find_hours method
  # day = 'Mon', time = 'morning'...
  def match_time(day, time)
    o = Opening.find_by(day: day, company_id: self.id)
    if check_hour(o) == true
      return_hours(time, o)
    else
      check_hour(o)
    end
  end

  def display_all_openings
    hours_array = []
    all_hours = Opening.where(company_id: self.id)
    all_hours.each do |o|
      if check_hour(o) == true
        hours_array << "#{o.day}:  #{ morning_format(o)} | #{noon_format(o)}"
      else
        check_hour(o)
      end
    end
    hours_array
  end

  # Formats the hours example: 06:05 
  def morning_format(o)
    if (o.morning_opens_at_hours && o.morning_opens_at_minutes && o.morning_closes_at_hours && o.morning_closes_at_minutes)
      morning_hours = "#{format '%02d', o.morning_opens_at_hours}:
      #{format '%02d', o.morning_opens_at_minutes} - 
      #{format '%02d', o.morning_closes_at_hours}:
      #{format '%02d', o.morning_closes_at_minutes}"
      morning_hours.gsub!(/\s/, '')
      morning_hours.gsub!(/-/, ' - ')
    else
      morning_hours = " - "
    end
  end

  def noon_format(o)
    if (o.morning_opens_at_hours && o.morning_opens_at_minutes && o.morning_closes_at_hours && o.morning_closes_at_minutes)
      noon_hours = "#{format '%02d', o.afternoon_opens_at_hours}:
      #{format '%02d', o.afternoon_opens_at_minutes} - 
      #{format '%02d', o.afternoon_closes_at_hours}:
      #{format '%02d', o.afternoon_closes_at_minutes}"
      noon_hours.gsub!(/\s/, '')
      noon_hours.gsub!(/-/, ' - ')
    else
      noon_hours = " - "
    end
  end

  # Returns day opening hours formatted for easy reading
  def allday_format(o)
    "#{morning_format(o)} | #{noon_format(o)}"
  end
  
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::V1::BaseController
  def index
    @companies = Company.all
  end
end

app/controllers/companies_controller.rb
# Companies
# todo - Make it dry
# require 'json'
# require 'open-uri'

class CompaniesController < ApplicationController
  include Pundit
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :authenticate_user!, only: %i[new create edit update review]

  def index
      @companies = policy_scope(Company.all.page params[:page]).order(created_at: :desc)
      # url = "http://localhost:3000/api/v1/companies"
      # company_serialized = URI.open(url).read
      # @companies = JSON.parse(company_serialized)#page params[:page])
  end

  def show
    @company = Company.find(params[:id])
    authorize @company
    @today = Time.now.strftime('%a')
    @tags = clean_show
    @days = %w[Mon Tue Wed Thu Fri Sat Sun]
    @sym_days = %i[mon tue wed thu fri sat sun]
    @c = 0
  end

  def new
    if user_signed_in?
      @company = Company.new
    else
      redirect_to new_user_session_path(from: 'add')
    end
  end

  def create
    @company = Company.new(name: params[:company][:name], user: current_user)
    if @company.save
      install_openings(@company)
      redirect_to company_mon_path(@company, day: "mon")
      flash[:notice] = " New Company: \n #{@company.name} was added."
    else
      # redirect_to companies_path(params: 'not-created') # To do: add error message
      flash[:notice] = 'Company not added. '
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    
  end

  def review
    @company = Company.find(params[:company_id])
    @today = Time.now.strftime('%a')
    @tags = clean_show
    @days = %w[Mon Tue Wed Thu Fri Sat Sun]
    @sym_days = %i[mon tue wed thu fri sat sun]
    @c = 0
    @all_openings = [
        @mon = Opening.create(day: 'Mon', company_id: @company.id),
        @tue = Opening.create(day: 'Tue', company_id: @company.id),
        @wed = Opening.create(day: 'Wed', company_id: @company.id),
        @thu = Opening.create(day: 'Thu', company_id: @company.id),
        @fri = Opening.create(day: 'Fri', company_id: @company.id),
        @sat = Opening.create(day: 'Sat', company_id: @company.id),
        @sun = Opening.create(day: 'Sun', company_id: @company.id)
        ]
  end

  private

  # Creates a div to be passed on the view to display each day's opening hours
  def install_openings(company)
      @mon = Opening.create(day: 'Mon', company_id: company.id),
      @tue = Opening.create(day: 'Tue', company_id: company.id),
      @wed = Opening.create(day: 'Wed', company_id: company.id),
      @thu = Opening.create(day: 'Thu', company_id: company.id),
      @fri = Opening.create(day: 'Fri', company_id: company.id),
      @sat = Opening.create(day: 'Sat', company_id: company.id),
      @sun = Opening.create(day: 'Sun', company_id: company.id)
  end

  def clean_show
    days = %i[ mon tue wed thu fri sat sun ]
    html_days = []
    days.each do |day|
      html_days << "<div clas='morning' style='padding: 0 #{closed?(day, :morning)};text-align: center;'>
      #{@company.find_hours[day][:morning]} </div>
      <div clas='noon' style='padding: 0 #{closed?(day, :noon)};text-align: center;'>#{@company.find_hours[day][:noon]}
      </div>"
    end
    html_days
  end

  # checks if opening is a closed day or 24h day
  def closed?(day, time)
    case @company.find_hours[day][time]
    when 'Closed'
      '35px'
    when '24H'
      '42px'
    else
      '16px'
    end
  end

  
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
edit

app/views/companies/index.html.erb
<div class="main-container container">
  <h1>Companies</h1>
  <div class="itens-container container">
    <% @companies.each do |company| %>
      <div class="each-item-container container">
        <h4><%= link_to "#{company.name}", company_path(company)  %></h4>
      </div>
    <% end %>    
    <!-- add 
      <div class="each-item-container container">
        
        <h4><%= link_to "Add your Company", new_company_path  %></h4
        
      </div>
    -->
  </div>

</div>
<div class="pag-grid pages-container">
  <%= paginate @companies %>
</div>

app/views/companies/new.html.erb
<div class="content-container container">
  <div class="new-company-container">
    <h1>Add your company</h1>
    <%= simple_form_for @company do |f| %>
      <%= f.input :name, label: "name" %>
      <%= f.submit %>
    <% end %>

  </div>
</div>

app/views/companies/review.html.erb
<div class="main-container container">
  <h1><%= @company.name %></h1>
  <div class="show-container container">
    <%= link_to "back", companies_path %>
    <h4>Opening Hours</h4>
    
    <!-- Creates a Div for every day of the week ( Opening.day: 'Mon' )-->
    <% @tags.each do |tag| %>
    
      <!-- Set bold and background if div's day is today -->
      <div class="each-day <%= "today" if @company.find_hours[@sym_days[@c]][:day] == @today %>">
        <h5><%= @days[@c] %></h5>
        <% @day_to_text = @company.find_hours[@sym_days[@c]][:day] %>
        <%= render html: tag.html_safe %>
        <%= link_to  "edit", action: "#{@day_to_text.downcase}", controller: "openings", from: 'review' %>
        <% @c += 1 %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/companies/show.html.erb
<div class="main-container container">
  <h1><%= @company.name %></h1>
  <div class="show-container container">
    <%= link_to "back", companies_path %>
    <h4>Opening Hours</h4>
    
    <!-- Creates a Div for every day of the week ( Opening.day: 'Mon' )-->
    <% @tags.each do |tag| %>
    
      <!-- Set bold and background if div's day is today -->
      <div class="each-day <%= "today" if @company.find_hours[@sym_days[@c]][:day] == @today %>">
        <h5><%= @days[@c] %></h5>
        <%= render html: tag.html_safe %>
        
        <% @c += 1 %>
      </div>
    <% end %>
    
  </div>
</div>